name: Deploy to Jagoan Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Jagoan Hosting via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_HOST }}
        username: ${{ vars.FTP_USERNAME }}
        password: ${{ vars.FTP_PASSWORD }}
        protocol: ftp  # Change to 'sftp' if using SFTP
        port: ${{ vars.FTP_PORT }}
        local-dir: './dist'  # Adjust this to your build directory
        server-dir: ${{ vars.FTP_PATH }}
        state-name: '.ftp-deploy-sync-state.json' # Optional for incremental deploys
